name: Health Check

on:
  workflow_dispatch:
  push:
    branches: [ "bun_tsc", "main", "dev" ]
  pull_request:
    branches: [ "bun_tsc", "main", "dev" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: |
        bun install

    - name: eslint Lint check
      run: |
        bun run lint
 
    - name: Prettier Check
      run: |
        bun run format

    - name: web-ext Lint
      run: |
          bun run webext:lint

    - name: tsc
      run: |
          bun run tsc

    - name: Build
      run: |
        bun run build
